#%RAML 1.0 NamedExample
-
  "name": "Edward Jones"
  "accountNumber": "ABN100010010"
  email: "jones@example.com"
  phone: "303-333-3333"
  website: "www.example.com"
-
  "name": "Richa Jones"
  "accountNumber": "ABN100010012"
  email: "jones@example.com"
  phone: "303-333-3337"
  website: "www.example.com"
