#%RAML 1.0 NamedExample


  firstName: "Evan"
  lastName: "Sterling"
  email: "evan.sterling@example.com"
  department: "IT"
  title: "Project Manager"
  mailingStreet: "1801 Girad Pl"
  mailingCity: "Englewood"
  mailingState: "CO"
  mailingPostal: "80113"
  mailingCountry: "Denver"
  phone: "303-333-3331"
  website: "www.google.com"